name: 🛠

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.x'

jobs:
  build:
    name: Build Pintor
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Build package
        run: pnpm build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Run tests
        run: pnpm test
